import type { Metadata } from "next";
import "./globals.css";
import Header from "@/widgets/Header/Header";
import Footer from "@/widgets/Footer/Footer";


export const metadata: Metadata = {
  title: "NFT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <Header/>
          {children}
          <Footer/>
        </body>
    </html>
  );
}
